In [6]:
import fireducks.pandas as fd
import cv2
import pandas as pd
from PIL import Image
import numpy as np
import time

def load_image_fireducks(path):
    # Read image using OpenCV
    img = cv2.imread(path)
    if img is None:
        raise ValueError("Image not found or unable to read.")
    
    # Convert image to FireDucks DataFrame
    height, width, channels = img.shape
    reshaped_img = img.reshape(-1, 3)
    fdf = fd.DataFrame({'R': reshaped_img[:, 0], 'G': reshaped_img[:, 1], 'B': reshaped_img[:, 2]})
    return fdf

# Load image using OpenCV
def load_image_opencv(path):
    return cv2.imread(path)

# Load image using Pillow
def load_image_pillow(path):
    return Image.open(path)

# Benchmarking
def benchmark(func, path, task_name):
    start_time = time.time()
    result = func(path)
    end_time = time.time()
    print(f"{task_name}: {end_time - start_time:.4f} seconds")
    return result

image_path = "sample.jpg"  # Provide your image path

# Perform and Benchmark
print("=== Image Loading ===")
benchmark(load_image_opencv, image_path, "OpenCV Loading")
benchmark(load_image_pillow, image_path, "Pillow Loading")
benchmark(load_image_fireducks, image_path, "FireDucks Loading")

=== Image Loading ===
OpenCV Loading: 0.0122 seconds
Pillow Loading: 0.0002 seconds
FireDucks Loading: 0.0160 seconds

,R,G,B
0,101,88,36
1,98,85,33
2,100,87,35
3,98,85,33
4,102,88,39
...,...,...,...
3211259,243,227,144
3211260,240,223,144
3211261,239,222,143
3211262,238,220,143
3211263,242,224,147

=== Image Loading into FireDucks ===
FireDucks Loading: 0.0204 seconds

,R,G,B
0,101,88,36
1,98,85,33
2,100,87,35
3,98,85,33
4,102,88,39
...,...,...,...
3211259,243,227,144
3211260,240,223,144
3211261,239,222,143
3211262,238,220,143
3211263,242,224,147